### ISSUE TITLE
Clarification over large buffer sizes sought

### ISSUE THREAD

**Issue by andrewyatz** [dpryan79/libBigWig#21]
Hi. I encountered an issue yesterday when I accidentally set my buffer size to 8MB. It had the effect of quadrupling the cost of loading a bigwig file over HTTP. Once I noticed the problem and set it to the recommended size (`1<<17`) then performance was more reasonable. However I'm unclear as to how the buffer is being used internally and the impact it had on performance. When you request a portion of a remote file do you request a range that's the start+buffer size or is there something more cunning going on in the background?

Thanks and sorry for the request for clarification. I had thought I had totally messed up my Perl XS bindings for a bit of yesterday because they were worryingly slower than the equivalent kent bindings.

**Comment by dpryan79** [comment]
You've nailed it, when you request data from the remote server you do so in `bufSize` chunks. You don't really want this to be too big or too little, since in the former case you get a bunch of stuff you don't need, and in the latter case you start querying the server a lot. There's nothing really fancy going on with that (though if you have clever ideas then they're certainly welcome!).

The `bufSize` also determines how much of the file you need to store in memory. So using a large value can have unfortunate memory implications. The good news is that bigWig files tend to be small (and the individual zoom levels or interval sets even smaller), so you shouldn't need a huge value.

**Comment by andrewyatz** [comment]
Okay that's great to get clarification on that. Thank you
